<?php

require_once dirname(__DIR__) . '/php/php.php';

function loadTestData() {
    $testDataPath = __DIR__ . '/test-data.json';
    $testDataJson = file_get_contents($testDataPath);
    return json_decode($testDataJson, true);
}

function runCrossLanguageTests() {
    echo "=== PHP Cross-Language Signature Tests ===\n\n";
    
    $testData = loadTestData();
    $results = [
        'generated' => [],
        'validationResults' => []
    ];
    
    // Store original microtime function
    $originalMicrotime = 'microtime';
    
    // Generate signatures for each test case
    foreach ($testData['testCases'] as $index => $testCase) {
        echo "Test Case " . ($index + 1) . ": " . $testCase['name'] . "\n";
        
        // Mock microtime for consistent results
        $fixedTimestamp = $testCase['fixedTimestamp'];
        eval('function microtime($get_as_float = false) use ($fixedTimestamp) {
            return $get_as_float ? ($fixedTimestamp / 1000.0) : "";
        };');
        
        try {
            $signature = generateSignature(
                $testCase['body'],
                $testCase['integrationId'],
                $testCase['secretKey']
            );
            
            $results['generated'][$testCase['integrationId']] = $signature;
            echo "  Generated: $signature\n";
            
            // Validate the signature we just generated
            $isValid = validateSignature(
                $signature,
                $testCase['body'],
                $testCase['integrationId'],
                $testCase['secretKey'],
                300000 // 5 minute tolerance
            );
            
            echo "  Self-validation: " . ($isValid ? 'PASS' : 'FAIL') . "\n";
            
            if (!$isValid) {
                echo "  ERROR: Self-validation failed for " . $testCase['integrationId'] . "\n";
            }
            
        } catch (Exception $error) {
            echo "  ERROR: " . $error->getMessage() . "\n";
        }
        
        echo "\n";
    }
    
    // Test validation of signatures from other languages
    echo "=== Cross-Language Validation Tests ===\n";
    
    // Try to load signatures generated by other languages
    $signatureFiles = [
        'javascript-generated-signatures.json',
        'python-generated-signatures.json',
        'java-generated-signatures.json',
        'go-generated-signatures.json',
        'csharp-generated-signatures.json',
        'ruby-generated-signatures.json',
        'rust-generated-signatures.json',
        'typescript-generated-signatures.json'
    ];
    
    foreach ($signatureFiles as $filePath) {
        $fullPath = __DIR__ . '/' . $filePath;
        if (file_exists($fullPath)) {
            try {
                $otherSignatures = json_decode(file_get_contents($fullPath), true);
                $language = str_replace('-generated-signatures.json', '', $filePath);
                
                echo "\nValidating signatures from $language:\n";
                
                foreach ($testData['testCases'] as $testCase) {
                    $integrationId = $testCase['integrationId'];
                    if (isset($otherSignatures[$integrationId])) {
                        $isValid = validateSignature(
                            $otherSignatures[$integrationId],
                            $testCase['body'],
                            $integrationId,
                            $testCase['secretKey'],
                            300000
                        );
                        
                        echo "  $integrationId: " . ($isValid ? 'PASS' : 'FAIL') . "\n";
                    }
                }
            } catch (Exception $error) {
                echo "Error reading $filePath: " . $error->getMessage() . "\n";
            }
        }
    }
    
    // Save our generated signatures for other languages to validate
    $outputPath = __DIR__ . '/php-generated-signatures.json';
    file_put_contents($outputPath, json_encode($results['generated'], JSON_PRETTY_PRINT));
    echo "\nGenerated signatures saved to: $outputPath\n";
    
    return $results;
}

// Run tests if this file is executed directly
if (basename(__FILE__) === basename($_SERVER['SCRIPT_NAME'])) {
    runCrossLanguageTests();
}

?>
