#!/bin/bash

# Cross-Language Signature Test Runner
# This script runs signature generation and validation tests across all supported languages

set -e  # Exit on any error

echo "========================================"
echo "Cross-Language Signature Test Suite"
echo "========================================"
echo ""

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to run a test and capture output
run_test() {
    local language=$1
    local command=$2
    local dir=$3
    
    echo "----------------------------------------"
    echo "Running $language tests..."
    echo "----------------------------------------"
    
    if [ -d "$dir" ]; then
        cd "$dir"
        if eval "$command"; then
            echo "✅ $language tests completed successfully"
        else
            echo "❌ $language tests failed"
            return 1
        fi
        cd ..
    else
        echo "⚠️  $language directory not found: $dir"
        return 1
    fi
    echo ""
}

# Change to the signature-utils directory (parent of _test)
cd "$(dirname "$0")/.."

# Clean up any existing generated signature files
echo "Cleaning up previous test results..."
find . -name "generated-signatures.json" -delete
echo ""

# Track which tests passed/failed
declare -a passed_tests=()
declare -a failed_tests=()

# JavaScript/Node.js tests
if command_exists node; then
    if run_test "JavaScript" "node _test/cross-language-test.js" "."; then
        passed_tests+=("JavaScript")
    else
        failed_tests+=("JavaScript")
    fi
else
    echo "⚠️  Node.js not found, skipping JavaScript tests"
    echo ""
fi

# Python tests
if command_exists python3; then
    if run_test "Python" "python3 _test/cross_language_test.py" "."; then
        passed_tests+=("Python")
    else
        failed_tests+=("Python")
    fi
else
    echo "⚠️  Python3 not found, skipping Python tests"
    echo ""
fi

# PHP tests
if command_exists php; then
    if run_test "PHP" "php _test/cross_language_test.php" "."; then
        passed_tests+=("PHP")
    else
        failed_tests+=("PHP")
    fi
else
    echo "⚠️  PHP not found, skipping PHP tests"
    echo ""
fi

# TypeScript tests (if TypeScript is available)
if command_exists tsc && command_exists node; then
    echo "----------------------------------------"
    echo "Running TypeScript tests..."
    echo "----------------------------------------"
    if [ -d "typescript" ]; then
        cd typescript
        if tsc typescript.ts && node typescript.js; then
            echo "✅ TypeScript tests completed successfully"
            passed_tests+=("TypeScript")
        else
            echo "❌ TypeScript tests failed"
            failed_tests+=("TypeScript")
        fi
        cd ..
    else
        echo "⚠️  TypeScript directory not found"
        failed_tests+=("TypeScript")
    fi
    echo ""
else
    echo "⚠️  TypeScript compiler not found, skipping TypeScript tests"
    echo ""
fi

# Go tests
if command_exists go; then
    echo "----------------------------------------"
    echo "Running Go tests..."
    echo "----------------------------------------"
    if [ -d "go" ]; then
        cd go
        # Note: Go test would need to be implemented
        echo "⚠️  Go cross-language test not yet implemented"
        cd ..
    else
        echo "⚠️  Go directory not found"
    fi
    echo ""
else
    echo "⚠️  Go not found, skipping Go tests"
    echo ""
fi

# Java tests
if command_exists javac && command_exists java; then
    echo "----------------------------------------"
    echo "Running Java tests..."
    echo "----------------------------------------"
    if [ -d "java" ]; then
        cd java
        # Note: Java test would need to be implemented
        echo "⚠️  Java cross-language test not yet implemented"
        cd ..
    else
        echo "⚠️  Java directory not found"
    fi
    echo ""
else
    echo "⚠️  Java not found, skipping Java tests"
    echo ""
fi

# Summary
echo "========================================"
echo "Test Results Summary"
echo "========================================"

if [ ${#passed_tests[@]} -gt 0 ]; then
    echo "✅ Passed tests (${#passed_tests[@]}):"
    for test in "${passed_tests[@]}"; do
        echo "   - $test"
    done
    echo ""
fi

if [ ${#failed_tests[@]} -gt 0 ]; then
    echo "❌ Failed tests (${#failed_tests[@]}):"
    for test in "${failed_tests[@]}"; do
        echo "   - $test"
    done
    echo ""
fi

# Cross-validation summary
echo "Cross-Language Validation:"
echo "Generated signature files can be found in each language directory."
echo "Each test validates signatures generated by other languages when available."
echo ""

if [ ${#failed_tests[@]} -eq 0 ]; then
    echo "🎉 All available tests passed!"
    exit 0
else
    echo "⚠️  Some tests failed. Check the output above for details."
    exit 1
fi
